/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
   extend: {
        colors: {
        'brand-color-1': '#A67637',
        'brand-color-2': '#1A4855',
        'brand-color-3': '#5A0C0D',
        'brand-color-4': '#687E8C',
        'brand-color-5': '#E6E1DE',
        'brand-color-6': '#F9F9F9',
        'bg-color-6': '#10101D',
        'bg-color-7': '#F9F9F9',
      },
      padding: {
        '1': '4px',
        '2': '8px',
        '3': '16px',
        '4': '24px',
        '5': '32px',
        '6': '40px',
        '7': '48px',
        '8': '56px',
        '9': '64px',
        '10': '96px',
        '11': '128px',
        'side-padding': '104px',
      },
      borderRadius: {
        'button-l': '64px',
        'button-s': 'var(--button-corner-radius-l)',
        'cards': '24px',
        'field': '65px',
        'sm': '4px',
        'md': '8px',
        'lg': '32px',
        'xl': '64px',
        'button-md': 'var(--spacing-radius-md)',
        'button-sm': 'var(--spacing-radius-sm)',
        'button-lg': 'var(--spacing-radius-lg)',
        'button-xl': 'var(--spacing-radius-xl)',
        'card-md': 'var(--spacing-radius-md)',
        'card-sm': 'var(--spacing-radius-sm)',
        'card-lg': 'var(--spacing-radius-lg)',
        'card-xl': 'var(--spacing-radius-xl)',
      },
       screens: {
        'desktop': '1400px',
        'tablet': '822px',
        'mobile-l': '430px',
        'mobile-s': '393px',
      },
      font: {
        'primary-font' : 'Manrope' ,
        'secondary-font' : 'Inter' ,
      },
      fontSize: {
        '1': '65px',
        '2': '44px',
        '3': '35px',
        '4': '28px',
        '5': '24px',
        '6': '18px',
        '7': '16px',
        '8': '14px',
        '9': '12px',
        '10': '10px',
        '11': '22px',
      },
      blur: {
        'blur-1': '5px',
        'blur-2': '10px',
        'blur-3': '20px',
        'blur-4': '40px',
        'blur-5': '80px',
        'blur-6': '100px',
      },
      width: {
        'button-icon-l': '36px',
        'button-icon-s': '24px',
      },
      height: {
        'button-icon-l': '36px',
        'button-icon-s': '24px',
      },
    },
  },
  plugins: [],
}